# Generated by Django 3.1.7 on 2021-07-21 07:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_PIC', models.FileField(blank=True, upload_to='user_images/')),
                ('Category', models.CharField(max_length=200, null=True)),
                ('Full_Address', models.TextField(max_length=500, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_M', models.CharField(max_length=100, null=True)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Summary', models.TextField(max_length=100, null=True)),
                ('Content', ckeditor.fields.RichTextField(null=True)),
                ('ImagesM', models.FileField(blank=True, upload_to='images/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
