# Generated by Django 3.1.7 on 2021-07-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0002_auto_20210721_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ImagesM',
            new_name='Image',
        ),
    ]
