# Generated by Django 3.1.7 on 2021-07-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0003_auto_20210721_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category_M',
            new_name='Category',
        ),
    ]
