# Generated by Django 3.1.7 on 2021-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0004_auto_20210721_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
