# Generated by Django 3.1.7 on 2021-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0005_auto_20210721_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Publised',
            field=models.BooleanField(default=False),
        ),
    ]
